server:
  port: 10000

# eureka 配置
eureka:
  instance:
    hostname: localhost  # Eureka 服务端的实例名称
  client:
    register-with-eureka: false  # 是否想eureka注册中心注册自己
    fetch-registry: false # false 表示自己是注册中心
    service-url: # 监控页面的地址, 默认是 http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: wzy-study-eureka

